const VITE_YOUTUBE_API_KEY_1 = "AIzaSyBiM4mVtA1F1rE-YWLj9wIbsITVa_s8DV4"
const VITE_YOUTUBE_API_KEY_2 = "AIzaSyB2dawIeXCPVMVRMGi9HP4P1K8jWFUFiGE"
const VITE_YOUTUBE_API_KEY_3 = "AIzaSyAMRmfswGign7NTgDXFHIfjMcfLHur2uRw"
const VITE_YOUTUBE_API_KEY_4 = "AIzaSyCqCjaawh784KtjxrRHT6jH-LiTmU0IfnQ"
const VITE_YOUTUBE_API_KEY_5 = "AIzaSyC0StHW4iIK78OrX6_4rLcIiQw6BoTvbs8"
const VITE_YOUTUBE_API_KEY_6 = "AIzaSyCzGiIoSEkOpR_QlrLh97f4CL_4bYZuk4Q"
const VITE_YOUTUBE_API_KEY_7 = "AIzaSyBs80dpOJtCdXOU64DVlm4IXA3hkoygTqY"
const VITE_YOUTUBE_API_KEY_8 = "AIzaSyAU5S1l4y-zN0LRwAD0BlB3l-J8_bsnGGI"
const VITE_YOUTUBE_API_KEY_9 = "AIzaSyCnxZN2N7kvafwwEOZH-JGyNOncKlBRS14"
const VITE_YOUTUBE_API_KEY_10 ="AIzaSyDrIk9wgDq41WHYxviD4JwWuK3G5-jDwyI"
const VITE_YOUTUBE_API_KEY_11 = "AIzaSyBmgldK8KNPdL_Benll13wDF5U4J6YcDSk"
const VITE_YOUTUBE_API_KEY_12 = "AIzaSyD3LGWALVqU_FqWYdghIgGwnyqu9onbraw"
const VITE_YOUTUBE_API_KEY_13 = "AIzaSyDMAjY5eRc2lq3YGsnr_uJ-PDlc5TwCqkA"
const VITE_YOUTUBE_API_KEY_14 = "AIzaSyBFCPK70dOHsmbaOFbAKQn9lh4aRWHV2eQ"


const arr = [
    VITE_YOUTUBE_API_KEY_1,
    VITE_YOUTUBE_API_KEY_2,
    VITE_YOUTUBE_API_KEY_3,
    VITE_YOUTUBE_API_KEY_4,
    VITE_YOUTUBE_API_KEY_5,
    VITE_YOUTUBE_API_KEY_6,
    VITE_YOUTUBE_API_KEY_7,
    VITE_YOUTUBE_API_KEY_8,
    VITE_YOUTUBE_API_KEY_9,
    VITE_YOUTUBE_API_KEY_10,
    VITE_YOUTUBE_API_KEY_11,
    VITE_YOUTUBE_API_KEY_12,
    VITE_YOUTUBE_API_KEY_13,
    VITE_YOUTUBE_API_KEY_14,
]

export default arr;

